workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS without signing
        script: |
          flutter build ios --release --no-codesign
      - name: Package IPA manually
        script: |
          mkdir -p Payload
          mkdir -p build/ios/ipa
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r build/ios/ipa/solo_leveling_app.ipa Payload
          rm -rf Payload
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - chinooknao@gmail.com
